### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by RoniHdz** [jerryluoaustin/Among-Us-Manager#1]
Hi, first I wanna say that tour bot is so good 👍. I hope if you can add a command which shows the current status of a game. For example, writing am.status <voice channel>, the bot shows the currently players (with their alive/death), and the other info. I guess that this feature will be useful for servers where chat messages lost by spam/flood.

**Comment by jerluo** [comment]
am.update resends the embed (the interface with all the stuff on it). I didn't list the command on the help list because I just use it to test things but I can add it to the description.
