### ISSUE TITLE
Option to make it so people who are alive alive mute as well as deafen.

### ISSUE THREAD

**Issue by t0mtee** [jerryluoaustin/Among-Us-Manager#2]
For privacy reasons

**Comment by jerluo** [comment]
One problem with this feature is that discord throttles voice change requests (muting or deafening) to 10 changes every 5 seconds. That would mean if games had more than 5 people, each muting/unmuting would take 5 seconds for it to go through. I'm open to other suggestions on how to implement this though.

**Comment by t0mtee** [comment]
> One problem with this feature is that discord throttles voice change requests (muting or deafening) to 10 changes every 5 seconds. That would mean if games had more than 5 people, each muting/unmuting would take 5 seconds for it to go through. I'm open to other suggestions on how to implement this though.

Hmm... maybe it would be good to mute all the alive people and put all the dead people in a separate voice chat which the owner of the server creates that cannot normally be seen or entered?

**Comment by jerluo** [comment]
I am working to add this and other game options

**Comment by jerluo** [comment]
the bot is updated with new game settings. am.help 2 to see them all, including the channel muting.
