### ISSUE TITLE
Bot stops responding to reactions every now and then

### ISSUE THREAD

**Issue by chris400** [jerryluoaustin/Among-Us-Manager#4]
What can I do to provide more information?
it is not the 24hrs restart, it happens more often.
ending and starting the game fixes it.

**Comment by jerluo** [comment]
Quick fix for now is to just type am.update which brings up the embed back and then reactions should work. I'm looking to see why this is a bug in the meantime.

**Comment by jerluo** [comment]
The issue should be fixed.
